### ISSUE TITLE
Choose backup folder manually

### ISSUE THREAD

**Issue by HarriBuh** [maelchiotti/LocalMaterialNotes#141]
While I highly appreciate the latest addition to your app - the automatic backup - I do not like the "download" folder of my phone to be chosen as the only available location.
I would rather choose my own, it's called "backups" and it's where every backup from other apps are stored.
So my request is: Let the user choose the location of the backup.

Cheers.

**Comment by maelchiotti** [comment]
I agree that it would be a great option indeed. I will work on it for the next release!

**Comment by uli-on** [comment]
> Documents is perfect
Yup. I learned that Android does not regard me as the owner of my phone and already began expanding my folder structure there.

**Comment by maelchiotti** [comment]
Ok, in the end, I still tested one of the unmaintained SAF packages and it works very well for my basic usage.

I will use it because it has only been unmaintained for a few months, so I expect someone to fork it at some point ; and because it fixes both the issue of saving a file anywhere AND choosing a custom backup folder.

So, glad to say this feature will be available in the next release!

**Comment by uli-on** [comment]
Yay!! Thanks!!
