### ISSUE TITLE
Add the link button to the toolbar

### ISSUE THREAD

**Issue by at-pyrix** [maelchiotti/LocalMaterialNotes#187]
Hey!

It would be nice for the editor to detect links and make them clickable. Also, a support for markdown `[text](link)` would be great too.

I think a floating button that toggles read/write mode could be helpful, just like [Quillpad](https://github.com/quillpad/quillpad).

Thanks.

**Comment by maelchiotti** [comment]
Hi, links should already be detected and made clickable. But you need to manually insert a space or newline after them.

They are not automatically detected when you paste text, however. This is handled by the [fleather](https://github.com/fleather-editor/fleather) library, so I don't have direct control over this sadly. Similarly, fleather does not support any markdown syntax, so I can't add support for the link syntax.

I've tried two other editor libraries actually, hoping to provide more feature in the editor. But one was too complicated, and the other one still in development.

Finally, an edit/read mode button is a great idea, I'll track this is a new issue and add it for the next release.

**Comment by at-pyrix** [comment]
Thanks for your response.

I was wondering, if we can't have the markdown syntax for links, can we have just the hyperlink?

A button to add a link and a title (just like reddit).

**Comment by maelchiotti** [comment]
The link button is missing from the toolbar indeed. It required a bit more code to implement so I left it out. But I'll also add it for the next release, because I agree it would be useful.

As for the library you linked, it is an Android one, but not a Flutter one, so I cannot use it. Even if I could, it's the editor library that handles that and that would need to implement it, so I'm afraid I can't do anything about the markdown syntax until a better editor library comes out.

_Don't worry!_

**Comment by at-pyrix** [comment]
Alright! I'll just keep this issue opened for now though. Just to serve as a reminder :)

**Comment by maelchiotti** [comment]
Done is #191, the link toolbar button will be available in the next release @at-pyrix!
