### ISSUE TITLE
Allow to organize the notes into folders

### ISSUE THREAD

**Issue by qupufu** [maelchiotti/LocalMaterialNotes#240]
would it be possible to allow sorting notes into folders? while I love the simplicity of this app, it can be difficult to manage a lot of notes.

**Comment by maelchiotti** [comment]
I will probably add the possibility to sort notes with labels (tags) when I find the time to do so (see #68). I agree managing hundreds of notes is probably difficult.

I think labels are better than folders because you can assign multiple labels to a single note, whereas you can put a not in only one folder. Would labels satisfy your needs?
