### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by Eliya-Manoj** [maelchiotti/LocalMaterialNotes#265]
It helps to remember birthdays, To-dos, Tasks, anniversary, ..., etc.

Support Labels for reminders - helps to create custom labels to categorise reminders like todo, birthdays, anniversary, ..., etc.

Reminder needs to contains Date, Time, Repeat ( day, week, month, year, custom )

Upcoming reminders are sorted first one to last ( it helps to identify upcoming reminders easily )

Notification for the Reminders

**Comment by maelchiotti** [comment]
Hi, thank you for your feature request !

I've already thought about that feature. But I really think it's out of the scope of this app, as it aims to be simple. Adding labels made sense as they allow to categorise the notes and would be useless by themselves
 However reminders feel like an entirely different feature that could be handled by a different, dedicated application.

I'll close the issue because I'm certain I won't add this. Hope you can still enjoy the app!
