### ISSUE TITLE
Widget to notes

### ISSUE THREAD

**Issue by ashwathrapolu** [maelchiotti/LocalMaterialNotes#312]
If not reminders, can you please add a widget option to a single note or multiple notes!

**Comment by maelchiotti** [comment]
I've tried this in #28. Sadly it's pretty much impossible. The tool I use to create the app (Flutter) doesn't support creating widgets. So I would have to code them in native code. Learning that could be doable, but even then I wouldn't be able to display the rich content of the notes at all (only Flutter can), so that would be pointless.

Maybe I'll try again when I add more types of notes (#303), because I would be able to render pure text, checklists and maybe markdown in a widget.
