### ISSUE TITLE
Improve the separation between notes tiles

### ISSUE THREAD

**Issue by maxongshD** [maelchiotti/LocalMaterialNotes#69]
I want to suggest an improvement 
 you need to add separators between notes on the main screen. (for both tiles and linear sorting).

![Screenshot_20240525-121344_Quillpad](https://github.com/maelchiotti/LocalMaterialNotes/assets/142055169/b43654af-e585-491d-86d8-28440a83d698)

**Comment by itsmartashub** [comment]
Having a clear separation between notes in both tile and linear sorting views would really help with readability and organisation.  
  
Since @maelchiotti  said that he's not into coloring the notes (want to avoid a very colorful app), perhaps we could consider a subtle alternative. For example, the MI Notes app uses soft, unobtrusive colors for note backgrounds, which might be a good compromise.
Another option could be an subdued outline view (maybe without shadows). This would keep the simple, elegant look while making it easy to see the difference between notes.


MI notes:
![1716639094920](https://github.com/maelchiotti/LocalMaterialNotes/assets/44645238/97239fec-16ca-4c48-87f4-bd140237c7e8)
![1716639094928](https://github.com/maelchiotti/LocalMaterialNotes/assets/44645238/b0ec954c-8da4-4688-a5c5-6ca60f1a6ad0)


Outline example (comming from [FossifyOrg Notes](https://github.com/FossifyOrg/Notes)):

![IMG_20240525_132700](https://github.com/maelchiotti/LocalMaterialNotes/assets/44645238/991e8e7a-780e-48fb-9644-e284041c6e3e)

**Comment by maelchiotti** [comment]
I do like how the Mi Notes look, I will give it a try and make it optional.

**Comment by maelchiotti** [comment]
@maxongshD @itsmartashub If you wish, feel free to try out the new notes tiles background option I added in #78 (an APK is built as an artifact) and tell me what you think! I designed it to be similar to Mi Notes and to be toggleable, like the separators.

**Comment by maelchiotti** [comment]
Implemented in #78.

**Comment by itsmartashub** [comment]
You're setting some standard with the speed of implementation of new suggestions, considering you're working alone.
Thanks so much for the update 🥹 I'll give the feedback as soon as I get a moment to try out the mentioned version
