### ISSUE TITLE
Import notes from Google Keep

### ISSUE THREAD

**Issue by Bertklq1** [maelchiotti/LocalMaterialNotes#71]
Import json files from google keep to material notes

**Comment by maelchiotti** [comment]
Hi, sadly this won't be possible, for the moment at least.

Google Keep uses their own data model, which is very different from the one used by the editor library I use ([parchment](https://github.com/fleather-editor/fleather/tree/master/packages/parchment). They also do not have the exact same formatting option, separate text notes from checklists...

The conversion would require a lot of code and support and thus I feel it's outside of the scope of the app. That's why I'm closing this.

Thank you anyway for your interest in Material Notes, feel free to open other issues!
